id: 'plain_html_list'
title: 'Plain HTML List'
theme: 'block__language_selector__plain_html_list'
templates_location: '/templates'
libraries: []
properties:
  plain_html_list:
    title: 'Plain HTML List'
    type: 'details'
    open: true
    states:
      visible:
        ':input[name="settings[look_and_feel][theme]"]':
          value: 'plain_html_list'
    properties:
      general:
        title: 'General'
        type: 'fieldgroup'
        properties:
          css:
            title: 'Enter custom css class for the component'
            type: 'textfield'
          text_transformation:
            title: 'Text transformation'
            type: 'select'
            default_value: [ 'default' ]
            options:
              default: 'Default'
              upper: 'Upper case'
              lower: 'Lower case'
              capitalize: 'Capitalize'
      display:
        title: 'Display options'
        type: 'fieldset'
        properties:
          items:
            title: 'Display options'
            type: 'fieldgroup'
            properties:
              show:
                title: 'Select items to display (select one at least)'
                type: 'checkboxes'
                default_value: [ 'icons', 'lang_code' ]
                states:
                  required:
                    ':input[name="settings[look_and_feel][theme]"]':
                      value: 'plain_html_list'
                required: true
                options:
                  icons: 'Icons'
                  lang_code: 'Language code'
                  lang_name: 'Language name'
              icon_height:
                title: 'Flag icon height (px)'
                type: 'number'
                default_value: 25
              icon_alignment:
                title: 'Icon alignment'
                type: 'select'
                default_value: [ 'left' ]
                options:
                  left: 'Left'
                  right: 'Right'
